### PR TITLE
#32 Create Top Navigator tab component

### LINKED ISSUE #32: Top navigation tab
Reusable top navigation component that switches between tabs in `/components`, required by several pages.

image
image

### PR DESCRIPTION
**Pull request by Ph1lipWu**
Create Top Navigator tabs
image

## Change Summary
**Create a top navtab component for later use**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

component use case:
```
const tabData = [
  { name: 'Task Details', content: <div>Content for Task Details</div> },
  { name: 'Other Details', content: <div>Content for Other Details</div> }
];

<TopNavtab tabs={tabData} />

```
## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

# Related issue

- Resolve #32

### CODE REVIEW

**Review by SeiKasahara — COMMENTED** [review]
I think you can use the blue style `penni-main` from `tailwind.config.ts`.
Reference the style definitions from `tailwind.config.ts` as many as possible

**Comment by Ph1lipWu** [comment]
> I think you can use the blue style `penni-main` from `tailwind.config.ts`. Reference the style definitions from `tailwind.config.ts` as many as possible

Thanks for the reminder. Committed a new version using the theme colour in the config.

**Review by yunho7687 — CHANGES_REQUESTED** [review]
the name should be top-nav-tab.tsx (please check the style-guide.md )

**Review by yunho7687 — APPROVED** [review]

**Comment by Ph1lipWu** [comment]
component use case:
const tabData = [
  { name: 'Task Details', content: <div>Content for Task Details</div> },
  { name: 'Other Details', content: <div>Content for Other Details</div> }
];

<TopNavtab tabs={tabData} />

**Pull request merged**
