### PR TITLE
issue15 create multistep signup form hooks and components.

### LINKED ISSUE #15: Sign in & Sign up
## Basic Information

create the sign in and sign up components
[Figma design](https://www.figma.com/design/bhSe5HkMJKKN0Bs1ZqSddi/Penni?node-id=5996-22124&t=w0t63mb6QaHbIOjN-0)

### PR DESCRIPTION
**Pull request by ArcueidShiki**
…ub.com>

This commit is not a final version of the issue, it finish the following parts:
1. Basic interaction sign up pages and components
2. Each input box can memorize previous user inputs when going back
3. Switch user function and submit form to different api based on current user type with console log formData
4. continue button, skip, Back button  works
5. TODO : furnish pages with CSS
6. Question: Do we need password and confirm password and user input validation? or we will do that later on.

## Change Summary
**[Briefly summarise the changes that you made. Just high-level stuff]**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [#15 ] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [x] The change has tests [yes]
- [x] The change has documentation [in commit message]

git cherry-pick commit-id to your local branch
run: npm run dev/ For testing the interaction of the basic page
## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

# Related issue

- Resolve #15

### CODE REVIEW

**Comment by ArcueidShiki** [comment]
TODO (incomplete):
beautify ugly CSS layout

**Comment by ArcueidShiki** [comment]
TODO:
1. Add "password box" and "confirm password box"
2. Make sure "progress bar" totally complete when all the registration complete
3. Do email check and Australia Standard Phone started with country code in drop down menu
4. write resuable bottom pop-up menu components

**Review by yunho7687 — CHANGES_REQUESTED** [review]
image
far from the Figma design, and please read the style-guide.md

**Comment by ArcueidShiki** [comment]
@yunho7687 This is no the the finial solution. I'll submit refresh and push a new patch after finishing styleing.
There are many components on this page. progressbar, bottom popup window, multistep form, image uploader, webcamera.
It consumes time more than I expected (btw I'm green at fronted), to make sure all the funtionality of user interfaces are working well.
I'll notify you, once I finished all the components above, almost here.

**Review by yunho7687 — APPROVED** [review]

**Pull request merged**
