### PR TITLE
Issue 13 create onboarding screens carousel like component

### LINKED ISSUE #13: Create Onboarding Screens ( carousel-like ) Component
## Basic Information
Create an onboarding screens component. These screens should be displayed when the user first opens the app, providing a carousel-like introduction to the app's key features and benefits.

## Requirements:
- Create a React component for the onboarding screens.
- Implement a carousel to navigate through the different onboarding slides.
-Navigation ("Prev/Next", progress step) 
- Include a skip button to allow users to bypass the onboarding process.
- Ensure smooth transitions between onboarding slides.
- Ensure a smooth transition from the onboarding screens to the main app interface.
- from each picture ensure colour change of time and battery according to image background
-note that after each next, there are consecutive dots at front bottom placement of the image that change shape when specifying which image the user is currently at

[Figma design](https://www.figma.com/design/bhSe5HkMJKKN0Bs1ZqSddi/Penni?node-id=5996-22124&t=w0t63mb6QaHbIOjN-0)

image

### PR DESCRIPTION
**Pull request by keyman015**
## Change Summary
This PR introduces the on-boarding component that, when called opens the on-boarding slides (which are passed as props) and transitions between the slides like a carousel with a smooth sliding transition. It is also possible to swipe across using a touchscreen (like a phone). After completing the on-boarding slides (skipped or finished), it replaces the component with the following content passed to the component.

This PR solves https://github.com/codersforcauses/penni/issues/13 and https://github.com/codersforcauses/penni/issues/30.

### Change Form
N/A (there was no form on the issues)

## Other Information
To support this carousel feature for on-boarding, a new package was installed, requiring a docker rebuild (`docker compose down -v` then `docker compose up --build`)
Note: Custom tailwind values used were approved by Juile?

# Related issue

- Resolve #13

### CODE REVIEW

**Review by yunho7687 — CHANGES_REQUESTED** [review]
great job! Could you change the name following the style-guide.md in the client fold( change the file name from `OnBoarding.tsx` to `on-boarding.tsx`

**Review by Julie-Salazar — APPROVED** [review]
Lgtm! I agree with Yunho just change to kebab case

**Review by yunho7687 — APPROVED** [review]

**Comment by yunho7687** [comment]
there are some type check errors. need to fix that before can be merged
Screenshot 2024-07-11 at 4 07 25 PM

**Comment by keyman015** [comment]
> there are some type check errors. need to fix that before can be merged Screenshot 2024-07-11 at 4 07 25 PM

Yeah sorry, I'm trying to fix that now for you :)

**Comment by yunho7687** [comment]
well done!

**Pull request merged**
